n_steps: 24
batch_size: 2048
gae_lambda: 0.95
gamma: 0.99
n_epochs: 5
ent_coef: 0.005
learning_rate: 0.001
clip_range: 0.2
policy_kwargs: "dict(activation_fn=nn.ELU, net_arch=dict(pi=[128, 128], vf=[128, 128]))"
