# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Configuration for the TurtleBot3 Burger AMR asset.

The robot is loaded from a pre-converted USD (``descriptions/turtlebot3/model.usd``) generated by
``core/utils/convert_urdf_to_usd.py`` from ``descriptions/turtlebot3/model.urdf``. Loading a static
USD keeps the runtime free of the URDF importer extension, which is not headless-safe and hangs
inside the container. The wheels are differential-drive joints (``wheel_left_joint`` /
``wheel_right_joint``) with matching joint origins so positive joint velocity drives the robot
forward along +x; their drive gains are baked into the USD.
"""

from __future__ import annotations

import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import IdealPDActuatorCfg
from isaaclab.assets import ArticulationCfg

_AMR_URDF_DIR = os.path.dirname(os.path.abspath(__file__))
_AMR_USD_PATH = os.path.join(_AMR_URDF_DIR, "turtlebot3", "model.usd").replace("\\", "/")

AMR_BURGER_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=f"{_AMR_USD_PATH}",
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            max_depenetration_velocity=10.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.1),
        rot=(1.0, 0.0, 0.0, 0.0),
        joint_pos={"wheel_left_joint": 0.0, "wheel_right_joint": 0.0},
    ),
    actuators={
        "wheels": IdealPDActuatorCfg(
            joint_names_expr=["wheel_left_joint", "wheel_right_joint"],
            stiffness=0.0,
            damping=0.5,
            effort_limit=5.0,
        ),
    },
)
